services:
  mongodb:
    image: mongo:8
    container_name: study-now-mongodb
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_APP_USERNAME: ${MONGO_APP_USERNAME}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}

    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo/init:/docker-entrypoint-initdb.d:ro

    networks:
      - study-now-internal

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --username \"$${MONGO_INITDB_ROOT_USERNAME}\" --password \"$${MONGO_INITDB_ROOT_PASSWORD}\" --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 }).ok' | grep 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  study-now-internal:
    driver: bridge

volumes:
  mongodb_data:
    name: study-now-mongodb-data
